from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import os
from datetime import date

def create_pdf(subjects, weak_topics, exam_date, hours_per_day, difficulty, plan):
    pdf_path = "study_plan.pdf"
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#6C63FF'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.grey,
        spaceAfter=20,
        alignment=TA_CENTER
    )

    info_style = ParagraphStyle(
        'Info',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#333333'),
        spaceAfter=6,
        leftIndent=10
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#6C63FF'),
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold'
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#444444'),
        spaceAfter=6,
        leading=16,
        leftIndent=5
    )

    story = []

    # Header
    story.append(Paragraph("AI Study Planner", title_style))
    story.append(Paragraph("Your Personalized Study Plan", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#6C63FF')))
    story.append(Spacer(1, 0.2*inch))

    # Plan Details
    story.append(Paragraph("Plan Details", heading_style))
    story.append(Paragraph(f"<b>Subjects:</b> {subjects}", info_style))
    story.append(Paragraph(f"<b>Weak Topics:</b> {weak_topics}", info_style))
    story.append(Paragraph(f"<b>Exam Date:</b> {exam_date}", info_style))
    story.append(Paragraph(f"<b>Hours Per Day:</b> {hours_per_day} hours", info_style))
    story.append(Paragraph(f"<b>Difficulty:</b> {difficulty}", info_style))
    story.append(Paragraph(f"<b>Generated On:</b> {date.today()}", info_style))
    story.append(Spacer(1, 0.15*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#DDDDDD')))
    story.append(Spacer(1, 0.15*inch))

    # Study Plan Content
    story.append(Paragraph("Your Study Plan", heading_style))

    for line in plan.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.08*inch))
            continue

        if line.startswith('##'):
            text = line.replace('##', '').strip()
            story.append(Paragraph(text, heading_style))
        elif line.startswith('#'):
            text = line.replace('#', '').strip()
            story.append(Paragraph(text, heading_style))
        elif line.startswith('*') and line.endswith('*'):
            text = line.replace('**', '')
            bold_style = ParagraphStyle(
                'Bold', parent=body_style,
                fontName='Helvetica-Bold',
                textColor=colors.HexColor('#333333')
            )
            story.append(Paragraph(text, bold_style))
        elif line.startswith('-') or line.startswith('•'):
            text = '• ' + line.lstrip('-•').strip()
            story.append(Paragraph(text, body_style))
        else:
            line = line.replace('**', '<b>', 1)
            line = line.replace('**', '</b>', 1)
            story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 0.3*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#DDDDDD')))
    story.append(Spacer(1, 0.1*inch))
    story.append(Paragraph(
        "Generated by AI Study Planner | Best of Luck!",
        subtitle_style
    ))

    doc.build(story)
    return pdf_path